services:
  - type: web
    name: chat-analysis-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
